version: "3.8"
services:
  rust-todo-mvc-db:
    image: postgres:16
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5438:5432
    networks:
      - sushil-networks
networks:
  sushil-networks:
